# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blog_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_title',
            field=models.CharField(default='(no title)', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
