# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171202_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_modified',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='date_published',
            field=models.DateTimeField(),
        ),
    ]
