# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171204_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='blog_published',
            field=models.BooleanField(default=False),
        ),
    ]
